Repository quarto-dev/quarto-cli, pull requests merged in 2023-05, with the labels that each got.

#5539 fix(contributing.md): typo and remove colons from section title
  .github/CONTRIBUTING.md
Labels: documentation

#5525 Update Manufacturer for Windows Installer
  package/src/windows/quarto.wxs
Labels: windows, installers

#5683 fix: add `opts_chunk_attr` to known knitr options
  src/resources/rmd/hooks.R
Labels: bug

#5531 feat(.github/DISCUSSION_TEMPLATE): add discussion templates
  .github/DISCUSSION_TEMPLATE/feature-requests.yml
  .github/DISCUSSION_TEMPLATE/q-a.yml
  .github/DISCUSSION_TEMPLATE/show-and-tell.yml
Labels: documentation

#5729 fix: remove section-divs as not for revealjs
  src/resources/editor/tools/vs-code.mjs
  src/resources/editor/tools/yaml/web-worker.js
  src/resources/editor/tools/yaml/yaml-intelligence-resources.json
  src/resources/schema/document-options.yml
Labels: documentation
