Repository quarto-dev/quarto-cli, pull requests merged in 2023-03, with the labels that each got.

#4595 Help rmarkdown find quarto bundled pandoc binary if none is found
  news/changelog-1.3.md
  src/resources/rmd/rmd.R
Labels: needs-discussion

#4732 Fix `embed` and `verbatim` knitr's engine for revealjs
  src/core/handlers/base.ts
  src/resources/rmd/hooks.R
  tests/docs/smoke-all/2023/03/09/code.R
  tests/docs/smoke-all/2023/03/09/revealjs-knitr-embed-verbatim.qmd
Labels: needs-discussion

#4804 Display warning if user doesn't have rights to change permissions #4474
  src/publish/confluence/api/index.ts
  src/publish/confluence/api/types.ts
  src/publish/confluence/confluence-verify.ts
  src/publish/confluence/confluence.ts
  tests/Pipfile.lock
  tests/configure-test-env.sh
Labels: confluence

#4932 only pass siteUrl for websites also for gh-pages provider
  news/changelog-1.3.md
  src/publish/gh-pages/gh-pages.ts
Labels: bug, needs-discussion
