Repository quarto-dev/quarto-cli, pull requests merged in 2023-06, with the labels that each got.

#5542 bug/5390-vimeo-newlink
  src/resources/extensions/quarto/video/_tests/test-suite.lua
  src/resources/extensions/quarto/video/video.lua
  tests/docs/smoke-all/video/video-smoke-test.qmd
Labels: video

#5681 bug/5622-too-many-confluence-permission-checks
  src/publish/confluence/api/index.ts
  src/publish/confluence/confluence-logger.ts
  src/publish/confluence/confluence-verify.ts
  src/publish/confluence/constants.ts
  tests/docs/smoke-all/confluence/abdul-abbas.png
  tests/docs/smoke-all/confluence/confluence-smoke-test.qmd
  tests/docs/smoke-all/confluence/elephant.png
  tests/docs/smoke-all/confluence/hanno.png
  tests/docs/smoke-all/confluence/images/abdul-abbas.png
  tests/docs/smoke-all/confluence/images/elephant.png
  tests/docs/smoke-all/confluence/images/hanno.png
  tests/docs/smoke-all/confluence/images/lin-wang.png
  tests/docs/smoke-all/confluence/images/surus.png
  tests/docs/smoke-all/confluence/lin-wang.png
  tests/docs/smoke-all/confluence/surus.png
Labels: publishing-confluence

#5805 fix: do not break words in website listings
  news/changelog-1.4.md
  src/resources/projects/website/listing/quarto-listing.scss
Labels: enhancement, listings

#5841 ci: no longer remove stale labels on updates
  .github/workflows/stale-needs-repro.yml
Labels: bug

#5857 fix: display metadata block even without title/subtitle
  src/resources/formats/html/pandoc/template.html
  src/resources/formats/html/templates/title-block.html
Labels: bug, enhancement

#5907 Don't break on paired shortcodes
  news/changelog-1.4.md
  src/core/lib/parse-shortcode.ts
  tests/docs/smoke-all/2023/06/13/5902.qmd
Labels: backport

#6010 ci: remove "close notes" from the stale message
  .github/workflows/stale-needs-repro.yml
Labels: enhancement
