Repository quarto-dev/quarto-cli, pull requests merged in 2024-01, with the labels that each got.

#8364 lua, code-fold + annotations - only lift code annotation cells ahead of layout merging
  src/resources/filters/quarto-post/foldcode.lua
  tests/docs/smoke-all/2024/01/19/8354.qmd
  tests/docs/smoke-all/2024/01/19/8354.tex.snapshot
  tests/verify.ts
Labels: bug, regression

#8458 fix: improve footer alignment for sm/md media breakpoint
  src/resources/projects/website/navigation/quarto-nav.scss
Labels: enhancement

#8492 chore: add example in plain text of qa discussion template
  .github/DISCUSSION_TEMPLATE/feature-requests.yml
  .github/DISCUSSION_TEMPLATE/q-a.yml
Labels: enhancement

#8465 fix 1.4 regression - shortcodes must resolve recursively.
  src/resources/filters/customnodes/shortcodes.lua
  tests/docs/smoke-all/2024/01/27/8464/.gitignore
  tests/docs/smoke-all/2024/01/27/8464/_quarto.yml
  tests/docs/smoke-all/2024/01/27/8464/_variables.yml
  tests/docs/smoke-all/2024/01/27/8464/about.qmd
  tests/docs/smoke-all/2024/01/27/8464/index.qmd
  tests/docs/smoke-all/2024/01/27/8464/styles.css
Labels: backport

#8489 Lua - escape unicode characters around LPEG library
  src/resources/filters/customnodes/shortcodes.lua
  src/resources/pandoc/datadir/lpegshortcode.lua
  src/resources/pandoc/datadir/readqmd.lua
  tests/docs/smoke-all/2024/01/29/8485.qmd
Labels: backport
