Repository quarto-dev/quarto-cli, pull requests merged in 2024-02, with the labels that each got.

#8553 Dashboard - correct title from code cell
  src/resources/filters/quarto-post/dashboard.lua
  tests/docs/smoke-all/dashboard/bugs/8552.qmd
Labels: backport

#8561 Website Nav - use text for aria-label
  src/project/types/book/book.ts
  src/project/types/types.ts
  src/project/types/website/website-navigation.ts
  src/resources/projects/website/templates/nav-after-body-postamble.ejs
Labels: backport

#8550 book crossref - fix references to non-chapters in unnumbered chapters
  src/project/types/book/book-crossrefs.ts
  tests/docs/smoke-all/2024/02/01/issue-8514/.gitignore
  tests/docs/smoke-all/2024/02/01/issue-8514/_quarto.yml
  tests/docs/smoke-all/2024/02/01/issue-8514/cover.png
  tests/docs/smoke-all/2024/02/01/issue-8514/index.qmd
  tests/docs/smoke-all/2024/02/01/issue-8514/intro.qmd
  tests/docs/smoke-all/2024/02/01/issue-8514/references.bib
  tests/docs/smoke-all/2024/02/01/issue-8514/references.qmd
  tests/docs/smoke-all/2024/02/01/issue-8514/summary.qmd
  tests/smoke/smoke-all.test.ts
Labels: bug, backport

#8570 Website Search - fuse.js performance
  src/resources/projects/website/search/quarto-search.js
Labels: bug, backport

#8549 feat: add documentation issue template
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: documentation

#8728 lua,latex - do not crash with empty floats
  src/resources/filters/customnodes/floatreftarget.lua
  tests/docs/smoke-all/2024/02/13/empty-floats.qmd
Labels: backport

#8764 `quarto use` support for non-empty directories
  src/command/use/commands/template.ts
  src/extension/install.ts
  tests/smoke/use/template.test.ts
  tests/verify.ts
Labels: use

#8784 Correctly normalize to forward slash the path when creating tar.gz for Posit Connect deploys
  src/publish/common/bundle.ts
Labels: backport

#8856 Fix a regression with detecting latex dependencies knit_meta in books
  src/resources/rmd/execute.R
  tests/docs/smoke-all/2024/02/22/8843/.gitignore
  tests/docs/smoke-all/2024/02/22/8843/_quarto.yml
  tests/docs/smoke-all/2024/02/22/8843/index.qmd
Labels: backport
