Repository quarto-dev/quarto-cli, pull requests merged in 2025-05, with the labels that each got.

#12625 light/dark toggle: fire window resize event
  news/changelog-1.7.md
  src/resources/formats/html/templates/quarto-html-before-body.ejs
Labels: backport, themes

#12653 light/dark toggle fire resize event
  src/resources/formats/html/templates/quarto-html-before-body.ejs
Labels: themes

#12812 [backport] Fix regression with keep-ipynb
  news/changelog-1.7.md
  src/command/render/render-contexts.ts
  src/command/render/render-files.ts
  src/core/jupyter/jupyter-embed.ts
  src/execute/jupyter/jupyter.ts
  src/execute/types.ts
  src/project/project-context.ts
  src/project/project-shared.ts
  src/project/types/single-file/single-file.ts
  tests/docs/smoke-all/2025/05/21/keep_ipynb_project/.gitignore
  tests/docs/smoke-all/2025/05/21/keep_ipynb_project/12780.qmd
  tests/docs/smoke-all/2025/05/21/keep_ipynb_project/_quarto.yml
  tests/docs/smoke-all/2025/05/21/keep_ipynb_single-file/12780.qmd
Labels: backport

#12793 Handle keep-ipynb correctly now that fileInformationCache is responsible for the cleaning
  news/changelog-1.8.md
  src/command/render/render-contexts.ts
  src/command/render/render-files.ts
  src/core/jupyter/jupyter-embed.ts
  src/execute/jupyter/jupyter.ts
  src/execute/types.ts
  src/project/project-context.ts
  src/project/project-shared.ts
  src/project/types/single-file/single-file.ts
  tests/docs/smoke-all/2025/05/21/keep_ipynb_project/.gitignore
  tests/docs/smoke-all/2025/05/21/keep_ipynb_project/12780.qmd
  tests/docs/smoke-all/2025/05/21/keep_ipynb_project/_quarto.yml
  tests/docs/smoke-all/2025/05/21/keep_ipynb_single-file/12780.qmd
Labels: backport
