Repository quarto-dev/quarto-cli, pull requests merged in 2025-01, with the labels that each got.

#11760 fix: Markdown support in listings templates
  src/resources/projects/website/listing/_filter.ejs.md
  src/resources/projects/website/listing/_metadata.ejs.md
  src/resources/projects/website/listing/_pagination.ejs.md
  src/resources/projects/website/listing/item-default.ejs.md
  src/resources/projects/website/listing/item-grid.ejs.md
  src/resources/projects/website/listing/listing-default.ejs.md
  src/resources/projects/website/listing/listing-grid.ejs.md
  src/resources/projects/website/listing/listing-table.ejs.md
  tests/docs/listings/_quarto.yml
Labels: needs-discussion

#11817 fix: restore HTML escape (`<%-`) for `listing.utilities.localizedString()`
  src/resources/projects/website/listing/_filter.ejs.md
  src/resources/projects/website/listing/_pagination.ejs.md
Labels: listings

#11997 [Backport] Fix regression in callout-title color for reveal dark
  news/changelog-1.6.md
  package/src/common/patches/revealjs-theme-0001-dracula.patch
  src/resources/formats/revealjs/quarto.scss
  src/resources/formats/revealjs/themes/dracula.scss
Labels: backport
